name: 'Auto approve/merge Dependabot (native) PR'
description: 'Auto approve and merge Dependabot (native) pull-requests.'
branding:
  icon: 'git-merge'
  color: blue
author: kocal
inputs:
  github-token:
    description: 'The GitHub token to use for auto-approving and auto-merging.'
    required: true
  update-type:
    description: 'Type of update for auto-merging, can be "major", "minor" or "patch".'
    default: 'all'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
